//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoCompany
    {
        public int Id { get; set; }
        public string NameCompany { get; set; }
        public string Logo { get; set; }
        public string Intro { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Hotline { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string MasoThue { get; set; }
        public string Website { get; set; }
        public string Facebook { get; set; }
        public string Youtube { get; set; }
        public string Twitter { get; set; }
        public string GooglePlus { get; set; }
        public string Pinterest { get; set; }
        public string Map { get; set; }
    }
}
