//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string SiteName { get; set; }
        public string Logo { get; set; }
        public string LogoWhite { get; set; }
        public string Favicon { get; set; }
        public string AppleIcon { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public string Author { get; set; }
        public string Designer { get; set; }
        public string Copyright { get; set; }
        public string ReplyTo { get; set; }
        public string Owner { get; set; }
        public string URL { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Hotline { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string MST { get; set; }
        public string LinkFacebook { get; set; }
        public string IdFacebook { get; set; }
        public string LinkYoutube { get; set; }
        public string IdYoutube { get; set; }
        public string LinkTwitter { get; set; }
        public string IdTwitter { get; set; }
        public string LinkInstagram { get; set; }
        public string IdInstagram { get; set; }
        public string LinkPinterest { get; set; }
        public string IdPinterest { get; set; }
        public string EmbedGoogleMap { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string StreetAddress { get; set; }
        public string Locality { get; set; }
        public string Region { get; set; }
        public string CountryName { get; set; }
        public string PostalCode { get; set; }
        public string GoogleSiteVerification { get; set; }
    }
}
