//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Title { get; set; }
        public string Alias { get; set; }
        public string Content { get; set; }
        public string MucGia { get; set; }
        public string TongQuan { get; set; }
        public string MatBang { get; set; }
        public string ChinhSach { get; set; }
        public string BanGiao { get; set; }
        public string Description { get; set; }
        public bool Published { get; set; }
        public bool Featured { get; set; }
        public string Image { get; set; }
        public string Tags { get; set; }
        public string ImageBanner { get; set; }
        public string Note { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKewords { get; set; }
        public string Author { get; set; }
        public string Robots { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public string UserId { get; set; }
        public double Views { get; set; }
    }
}
