//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> WardsId { get; set; }
        public Nullable<int> StreetId { get; set; }
        public string Address { get; set; }
        public string PropertyTypeId { get; set; }
        public string AspectId { get; set; }
        public string PriceTypeId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> PriceMin { get; set; }
        public Nullable<double> PriceMax { get; set; }
        public Nullable<double> Acreage { get; set; }
        public Nullable<double> AcreageMin { get; set; }
        public Nullable<double> AcreageMax { get; set; }
        public bool Published { get; set; }
        public bool Featured { get; set; }
        public string Image { get; set; }
        public string NameContact { get; set; }
        public string AddressContact { get; set; }
        public string PhoneNumberContact { get; set; }
        public string EmailContact { get; set; }
        public string Note { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKewords { get; set; }
        public string Author { get; set; }
        public string Robots { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public string UserId { get; set; }
        public double Views { get; set; }
    }
}
