//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Về công ty.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu chuẩn chất lượng.
        /// </summary>
        public static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rực Liễn, Thủy Sơn, Thủy Nguyên, Hải Phòng.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@namthuangroup.com.
        /// </summary>
        public static string CompanyEmail {
            get {
                return ResourceManager.GetString("CompanyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty TNHH Nam Thuận.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0225 3642 408.
        /// </summary>
        public static string CompanyPhoneNumber {
            get {
                return ResourceManager.GetString("CompanyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ với chúng tôi.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống quản trị.
        /// </summary>
        public static string CorporateGovernance {
            get {
                return ResourceManager.GetString("CorporateGovernance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSR.
        /// </summary>
        public static string CSR {
            get {
                return ResourceManager.GetString("CSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập đoàn Nam Thuận tự hào là công ty may mặc cung cấp các dịch vụ chất lượng hàng đầu trong khu vực. Chất lượng của sản phẩm cùng phong cách làm việc đã tạo nên thương hiệu của Tập đoàn Nam Thuận với tinh thần không ngừng học hỏi: &lt;q&gt;Luôn luôn đổi mới, hướng tới tương lai&lt;/q&gt;..
        /// </summary>
        public static string DesAboutUs {
            get {
                return ResourceManager.GetString("DesAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tại Nam Thuận, trái tim chúng ta hòa chung nhịp đập với cuộc đấu tranh của Người dân và Cộng đồng.
        /// </summary>
        public static string DesCSR {
            get {
                return ResourceManager.GetString("DesCSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đa dạng hóa kiểu dáng, chất lượng - Thiết kế bắt kịp xu hướng - Giá thành hợp lý - Năng lực sản xuất lớn.
        /// </summary>
        public static string DesProductCategory {
            get {
                return ResourceManager.GetString("DesProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử phát triển.
        /// </summary>
        public static string DevelopmentHistory {
            get {
                return ResourceManager.GetString("DevelopmentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiến lược phát triển.
        /// </summary>
        public static string DevelopmentStrategy {
            get {
                return ResourceManager.GetString("DevelopmentStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đa dạng và Chất lượng.
        /// </summary>
        public static string DiversityAndQuality {
            get {
                return ResourceManager.GetString("DiversityAndQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm nổi bật.
        /// </summary>
        public static string FeaturedProduct {
            get {
                return ResourceManager.GetString("FeaturedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên công ty.
        /// </summary>
        public static string FormCompanyName {
            get {
                return ResourceManager.GetString("FormCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung nhắn.
        /// </summary>
        public static string FormMessage {
            get {
                return ResourceManager.GetString("FormMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string FormName {
            get {
                return ResourceManager.GetString("FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string FormPhoneNumber {
            get {
                return ResourceManager.GetString("FormPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu về.
        /// </summary>
        public static string IntroduceAbout {
            get {
                return ResourceManager.GetString("IntroduceAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus blandit massa enim. Nullam id varius nunc. Vivamus bibendum magna ex, et faucibus lacus venenatis eget. Suspendisse potenti. Curabitur euismod facilisis neque, eu malesuada diam finibus non. Nullam nec vehicula leo. Morbi porta ante eu feugiat mollis..
        /// </summary>
        public static string IntroHome2 {
            get {
                return ResourceManager.GetString("IntroHome2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VI.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết trang.
        /// </summary>
        public static string LinkPage {
            get {
                return ResourceManager.GetString("LinkPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        public static string MenuAboutUs {
            get {
                return ResourceManager.GetString("MenuAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string MenuProduct {
            get {
                return ResourceManager.GetString("MenuProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam Thuận Group.
        /// </summary>
        public static string NamThuanGroup {
            get {
                return ResourceManager.GetString("NamThuanGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoặc.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tác của chúng tôi.
        /// </summary>
        public static string OurPartner {
            get {
                return ResourceManager.GetString("OurPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm của chúng tôi.
        /// </summary>
        public static string OurProduct {
            get {
                return ResourceManager.GetString("OurProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy liên hệ với chúng tôi.
        /// </summary>
        public static string PleaseContactUs {
            get {
                return ResourceManager.GetString("PleaseContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục sản phẩm.
        /// </summary>
        public static string ProductCategories {
            get {
                return ResourceManager.GetString("ProductCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quy trình sản xuất.
        /// </summary>
        public static string ProductionProcess {
            get {
                return ResourceManager.GetString("ProductionProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại sản phẩm.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quy trình kiểm soát chất lượng.
        /// </summary>
        public static string QualityControlProcess {
            get {
                return ResourceManager.GetString("QualityControlProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ nhanh.
        /// </summary>
        public static string QuickContact {
            get {
                return ResourceManager.GetString("QuickContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang gửi.
        /// </summary>
        public static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đội ngũ nhân sự.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị thành viên.
        /// </summary>
        public static string SubordinateUnits {
            get {
                return ResourceManager.GetString("SubordinateUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm kinh nghiệm.
        /// </summary>
        public static string YearOfExperience {
            get {
                return ResourceManager.GetString("YearOfExperience", resourceCulture);
            }
        }
    }
}
